apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JyothiKumar37/full_stack_chatapp.git
    targetRevision: master
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: chatapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
